name: main

on:
  push: ~
  workflow_dispatch: ~

jobs:
  ci:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
          cache: true
      - name: Install
        run: flutter pub get
      - name: Lint
        run: |
          flutter analyze